# Configurações da Aplicação de Impressão Espaço Vista

# Porta em que o servidor web irá rodar
server.port=8081

# Nome do arquivo de log onde os registros de impressão serão salvos
log.filename=logs.txt

# Arquivo que armazena o próximo número de registro.
# Em produção, preferencialmente use ETIQUETAS_SEQUENCE_FILE.
sequence.file=